goodbye:
  cooldown:
    seconds: 45
  messages:
    - "Bis dann"
    - Wiedersehen
    - "Auf Wiedersehen"
    - Bye
    - Byebye
    - Goodbye
    - Tschuß
    - Tschuuuuß
    - Tschus
    - Tschuuuuus
    - BB
    - Ciao
    - Tschüss
    - GN
    - Cya
    - Mach's gut!
greeting:
  messages:
    - "Huhu %s"
    - "Hi %s"
    - "Hii %s"
    - "Hiii %s"
    - "Hallo %s"
    - "Hellu %s"
    - "Hoi %s"
    - "Hey %s"
    - "Heyy %s"
    - "Heyyy %s"
    - "Tach %s"
    - "Tachchen %s"
    - "Moin %s"
    - "Moinsen %s"
  emoticons:
    - ":)"
    - ":D"
    - "(:"
    - "^_^"
    - "=D"
    - "=)"
    - "(="
    - "=]"
    - ":]"
    - "[:"
    - "（*＾-＾*）"
    - "(*^_^*)"
    - "(•_•)"
    - "( ﾉ ﾟｰﾟ)ﾉ"
welcome:
  messages:
    - "Willkommen %s"
    - "Willkommen %s!"
    - "Herzlich Willkommen %s"
    - "Herzlich Willkommen %s!"
reconnect:
  cooldown:
    seconds: 300
    welcomeback_seconds: 20
  messages:
    - "Welcome back %s"
    - "WB %s"
    - "Willkommen zurück %s"
pattern:
  chat:
    - "<(.*)> (.*)"
    - "\\[.*\\] (.*) .*> (.*)"
  join:
    - "(.*) joined the game"
    - "\\[\\+\\] (.*)"
  leave:
    - "(.*) left the game"
    - "\\[\\-\\] (.*)"
  welcome:
    - ".* Willkommen > Wir begr.*en (.*) zum ersten Mal auf .*!"
show-errors: false
